### ISSUE TITLE
NullReference in JSchema

### ISSUE THREAD

**Issue by jeme** [dotJEM/json-index#1]
```
message: "An error has occurred."
exceptionMessage: "Object reference not set to an instance of an object."
exceptionType: "System.NullReferenceException"
stackTrace:
 at DotJEM.Json.Index.Schema.JSchema.b__0(JSchema property) in f:\___\external\json-index\DotJEM.Json.Index\Schema\JSchema.cs:line 137
 at System.Linq.Enumerable.d__14`2.MoveNext()
 at System.Linq.Enumerable.d__88`1.MoveNext()
 at System.Linq.Enumerable.d__14`2.MoveNext()
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
 at System.Linq.Enumerable.d__81`1.MoveNext()
 at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
 at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
 at DotJEM.Json.Index.Searching.MultiFieldQueryParser..ctor(IStorageIndexindex, String query) in f:\___\external\json-index\DotJEM.Json.Index\Searching\MultiFieldQueryParser.cs:line 40
 at DotJEM.Json.Index.Searching.LuceneQueryBuilder.Build(String query) in f:\___\external\json-index\DotJEM.Json.Index\Searching\IQueryBuilder.cs:line 40
 at DotJEM.Json.Index.Searching.LuceneSearcher.Search(String query) in f:\___\external\json-index\DotJEM.Json.Index\Searching\ILuceneSearcher.cs:line 42
 at DotJEM.Json.Index.LuceneStorageIndex.Search(String query) in f:\___\external\json-index\DotJEM.Json.Index\IStorageIndex.cs:line 117
 at DotJEM.Web.Host.Providers.Services.ContentService.Get(String contentType,Int32 skip, Int32 take) in f:\___\external\web-host\DotJEM.Web.Host\Providers\Services\ContentService.cs:line 43
 at _____________.Controllers.ContentController.Get(String contentType, Int32 skip, Int32 take) in f:\___\Server\___\Controllers\ContentController.cs:line 39
 at lambda_method(Closure , Object , Object[] )
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Objectinstance, Object[] arguments)
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()

---End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()
```

**Comment by jeme** [comment]
Cannot reproduce
